Log:
  basePath: ../stackUIpro/logs
  fileForReadPath: /last_dir.txt
  nodeId: 3
  recordLogFileName: /allNodes.log
Srt:
  entry1:
  - 3
  - 3
  - 0
  entry2:
  - 2
  - 2
  - 1
  entry3:
  - 1
  - 1
  - 1
  entry4:
  - 4
  - 4
  - 1
  entry5:
  - 5
  - 5
  - 1
  nodeID: 3
aquasent:
  baudrate: 115200
  port: /dev/ttyUSB1
clientsocket:
  address: 192.168.2.106
  correlatethreadshort: 0.1
  cycleprefixms: 20
  gain: 0.01
  port: 80
  samplerate: 80000
drt:
  nodeID: 3
drtPlus:
  nodeID: 3
fskclient:
  address: 192.168.2.106
  correlatethreadshort: 0.1
  cycleprefixms: 20
  gain: 0.2
  port: 80
  readcycle: 300
  samplerate: 80000
  transmitAmp: 0.02
fsknewclient:
  address: 192.168.2.106
  correlatethreadshort: 0.1
  cycleprefixms: 20
  datasize: 42
  gain: 0.2
  port: 80
  readcycle: 30
  samplerate: 80000
  transmitAmp: 0.02
newAloha:
  MacId: 3
  MinReSendTime: 30
  ReSendTimeRange: 10
qpskclient:
  address: 192.168.2.106
  datasize: 1024
  port: 80
  qpsknumchannel: 4
  readcycle: 65535
  rxgain: 0.2
  samplerate: 96000
  threshold: 0.1
  txgain: 0.005
server:
  port: 9082
simulatechannel:
  address: 127.0.0.1
  port: 30001
test:
  othernodeID:
  - 1
  - 2
  - 4
  - 5

  packetnum: 100
  seed: 5
  testmode: 1
  timeforhandshake: 50
  timeinterval:
  - 5
  - 10
trace:
  tracefile: C.log
  tracemode: 1
  tracepath: ./logs
  tracetime: data809
vbf:
  position:
  - 1
  - 1
  - 1
famantr:
  MacId: 3
  Maxtransitdistance: 500
D_CSMA:
  MacId: 3
  CW: 20 #初始窗口值
  BrocastTime: 20 #SINk节点开始发测试数据的时间
  maxtranstime: 0.33 #最大传输时延  