aquasent:
    port: /dev/ttyUSB1
    baudrate: 115200

clientsocket:
    address: 192.168.2.105
    port: 80
    samplerate: 80000
    gain: 0.01
    cycleprefixms: 20
    correlatethreadshort: 0.1

qpskclient:
    address: 192.168.2.105
    port: 80
    rxgain: 0.1
    txgain: 0.06
    threshold: 0.2
    qpsknumchannel: 4
    samplerate: 96000
    datasize: 1024
    readcycle: 30

fskclient:
    address: 192.168.2.105
    port: 80
    samplerate: 80000
    gain: 0.2
    cycleprefixms: 20
    correlatethreadshort: 0.1
    readcycle: 30
    transmitAmp: 0.005

fsknewclient:
    address: 192.168.2.105
    port: 80
    samplerate: 80000
    gain: 0.1
    transmitAmp: 0.06
    cycleprefixms: 20
    correlatethreadshort: 0.2
    readcycle: 30 
    datasize: 128
    
simulatechannel:
    address: 127.0.0.1
    port: 30001
    gobackidle: 3

Srt:
    nodeID: 5
    entry1: [0, 0, 0]
    entry2: [0, 0, 0]
    entry3: [0, 0, 0]
    entry4: [0, 0, 0]
    entry5: [0, 0, 0]

vbf:
    position: [1, 1, 1]
drt:
    nodeID: 5
    
drtPlus:
    nodeID: 5

Dbpcr:
    id: 5
    x: 0
    y: 100
    z: 200
    depthThreshold: 0
    
server:
    port: 9080

test:
    testmode: 0
    seed: 10
    timeinterval: [20, 30]
    othernodeID: [2, 3, 4]
    packetnum: 20
    timeforhandshake: 300

trace:
    tracemode: 0
    tracepath: ./tracefile/
    tracefile: E.log

newAloha:
    MacId: 5
    MinReSendTime: 10
    ReSendTimeRange: 5

routingLayerTest:
    isOpen: 1
    recordPath: ./net/testInfo/
    protocolName: 5_dbpcr
    isSource: 1
    packetnum: 100
    timeinterval: [20, 40]
